---
title: "Spaghetti Code"
author: "Joshua Ferrer-Lozano"
date: "2025-08-26"
output: html_document
---
```{r}

library(janitor)
library(tidyr)
library(tidyverse)
library(paletteer)
library(dplyr)
library(here)
library(zoo)
```

```{r}
# import data sets 

data_1 <- read.csv(here('data','QuebradaCuenca1-Bisley.csv'))
data_2 <- read.csv(here('data','QuebradaCuenca2-Bisley.csv'))
data_3 <-read.csv(here('data','QuebradaCuenca3-Bisley.csv'))

bisley_all <- bind_rows(data_1,data_2,data_3)

```

```{r}
bisley_all <- bisley_all %>% mutate(Sample_Date = as.Date(Sample_Date)) %>% arrange(Sample_ID, Sample_Date)
```
```{r}
bisley_all <- tolower(colnames(bisley_all))
```
```{r}
bisley_all
```

```{r}
# Create a function where it includes a function where it will compute rolling means based on the column name or nutrient name
bisley_all %>% mutate(across(c(k, no3_n, mg, ca, nh4_n), ~ as.numeric(as.character(.))))

```
```{r}
 bisley_all <- bisley_all %>% mutate(across(c(k, no3_n, mg, ca, nh4_n), ~ .x |>as.character() |>
 str_replace_all(",", "") |> str_trim() |> na_if("") |> as.numeric()))
```

```{r}
#originally was going to use rollmean function

bisley_all$K_rm <- rollmean(bisley_all$K,9,fill=NA,align="center")
bisley_all$NO3_rm <- rollmean(bisley_all$NO3.N,9,fill=NA,align="center")
bisley_all$Mg_rm <- rollmean(bisley_all$Mg,9,fill=NA,align="center")
bisley_all$Ca_rm <- rollmean(bisley_all$Ca,9,fill=NA,align="center")
bisley_all$NH4_rm <- rollmean(bisley_all$NH4.N,9,fill=NA,align="center")
```

```{r}
# 9 Month Moving Average
moving_average <- function(focal_date, Sample_Date, conc, wind_size_weeks) {
  #Which dates are in the window
  is_in_window <- (dates > focal_date - (wind_size_weeks / 2) * 7) &
    (dates < focal_date + (wind_size_weeks / 2) * 7)
  #find the associated concentrations
  window_conc <- conc[is_in_window]
  #calculate the mean
  result <- mean(window_conc)
  
  return(result)
}

```

```{r}
#Finding rolling average for ca
nutrients$sample_date <- as.Date(nutrients$sample_date)

ca_ma_once <- moving_average(focal_date = as.Date("1986-05-20"),
                             Sample_Date = nutrients$sample_date,
                             conc = nutrients$ca,
                             wind_size_weeks = 9)
```


```{r}
#Vverifying the solution
tiny_problem$Sample_date <- as.date(tiny_problem$sample_date)

ca_ma_once <- moving_average(focal_date = as.Date("2001-12-04"),
                             dates = tiny_problem$sample_date,
                             conc = tiny_problem$ca,
                             wind_size_weeks = 9)

```


